name: Metrics (TokyoNight)

on:
  workflow_dispatch: # permite rodar manualmente
  schedule:
    - cron: "0 */12 * * *" # atualiza a cada 12h

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Usuário alvo
          user: rafaelmagnog
          template: classic
          base: header, activity, community, repositories, metadata

          # Tema
          config_presets: tokyonight

          # Linguagens
          plugin_languages: yes
          plugin_languages_limit: 10
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          # Commits
          plugin_followup: yes
          plugin_followup_sections: repositories, user

          # Linhas de código
          plugin_lines: yes

          # Repositórios
          plugin_repositories: yes

          # Stargazers
          plugin_stargazers: yes
